toml
app = "newfly"

[env]
  WEBHOOK_URL = "https://newfly.fly.dev"
  GENERIC_TIMEZONE = "America/Mexico_City"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[mounts]
  source = "data"
  destination = "/home/node/.n8n"
